name: 🚀 .NET CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: 📦 Restore dependencies
        run: dotnet restore OPS.sln

      - name: 🏗️ Build solution
        run: dotnet build OPS.sln --no-restore --configuration Release

      - name: ✅ Run tests
        run: dotnet test OPS.sln --no-build --configuration Release --verbosity normal
